// Prisma 配置文件（用于 CLI 工具）
// - 本地开发：dotenv 加载 .env 文件
// - Docker 构建：从 Dockerfile 的 ENV 读取占位符 DATABASE_URL
// - Docker 运行：从 docker-compose 的 env_file 读取真实 DATABASE_URL

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
